
[workspace]
members = [
  "crates/p2p-raft",
  "crates/partitioner",
  "test-crates/memstore",
  # "test-crates/network-impl",
]

resolver = "3"

[workspace.dependencies]
derive_more = { version = "1", features = ["full"] }
maplit = "*"

openraft = { git = "https://github.com/maackle/openraft.git", features = [
  "type-alias",
] }
openraft-macros = { git = "https://github.com/maackle/openraft.git" }
openraft-memstore = { git = "https://github.com/maackle/openraft.git" }

futures = "*"
itertools = "*"
memstore = { path = "test-crates/memstore" }
nanoid = "*"
network-impl = { path = "test-crates/network-impl" }
parking_lot = "*"
rand = { version = "0.9" }
serde = "*"
tokio = { version = "1.0", features = ["full"] }
tracing = "*"
tracing-subscriber = "*"
