
[workspace]
members = [
  "crates/p2p-raft",
  "test-crates/memstore",
  "test-crates/network-impl",
]

resolver = "3"

[workspace.dependencies]
derive_more = { version = "1", features = ["full"] }
maplit = "*"

openraft = { git = "https://github.com/maackle/openraft.git", features = [
  "type-alias",
] }
openraft-macros = { git = "https://github.com/maackle/openraft.git" }
openraft-memstore = { git = "https://github.com/maackle/openraft.git" }

memstore = { path = "test-crates/memstore" }
network-impl = { path = "test-crates/network-impl" }
rand = "*"
tokio = { version = "1.0", features = ["full"] }
tracing = "*"
tracing-subscriber = "*"
