[package]
name = "partitioner"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true }
itertools = "*"
parking_lot = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
